// export const ErrorCode = {
//   VALIDATION_ERROR: 'VALIDATION_ERROR',
//   UNAUTHORIZED: 'UNAUTHORIZED',
//   TOKEN_EXPIRED: 'TOKEN_EXPIRED',
//   TOKEN_BLACKLISTED: 'TOKEN_BLACKLISTED',
//   FORBIDDEN: 'FORBIDDEN',
//   NOT_FOUND: 'NOT_FOUND',
//   CONFLICT: 'CONFLICT',
//   BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
//   RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
//   INTERNAL_ERROR: 'INTERNAL_ERROR',
//   SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
// } as const;

// export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
